FirstWebApp/ViewModels/BikeCreateViewModel.cs
using DAL.Moldels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FirstWebApp.ViewModels
{
    public class BikeCreateViewModel
    {
        public Bike New { get; set; }
        public List<Branch> AvailableBranches { get; set; }
    }
}

FirstWebApp/ViewModels/CarCreateViewModel.cs
using DAL.Moldels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FirstWebApp.ViewModels
{
    public class CarCreateViewModel
    {
        public Car New { get; set; }
        public List<Branch> AvailableBranches { get; set; }

    }
}

FirstWebApp/Controllers/BikeController.cs
using DAL.Moldels;
using DAL.Repositories;
using FirstWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApp.Controllers
{
    public class BikeController : Controller
    {
        private BranchRepository branchRepo;
        private BikeRepository bikeRepo;

        public BikeController()
        {
            bikeRepo = new BikeRepository();
            branchRepo = new BranchRepository();
        }

        public ActionResult Create()
        {
            var viewModel = new BikeCreateViewModel();
            viewModel.AvailableBranches = branchRepo.Get();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult CreatePost(BikeCreateViewModel model)
        {
            if (model.New.BranchId <= 0) { }
            else
                bikeRepo.Create(model.New);

            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {

            var bike = bikeRepo.Get();
            return View(bike);
        }

    }
}

FirstWebApp/Controllers/BranchController.cs
using DAL.Moldels;
using DAL.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApp.Controllers
{
    public class BranchController : Controller
    {
        private BranchRepository branchRepo;

        public BranchController()
        {
            branchRepo = new BranchRepository();
        }


        

        public ActionResult Create()
        {
            var branch = new Branch();           
            return View(branch);
        }

        [HttpPost]
        public ActionResult CreatePost(Branch model)
        {

            branchRepo.Create(model);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int BranchId) // index view must return BranchId 
        {
            var branch = new Branch();
            branch = branchRepo.GetById(BranchId); 
            return View(branch);
        }

        [HttpPost]
        public ActionResult EditPost(Branch model)
        {
            if (model.Id <= 0) { }
            else
                branchRepo.Edit(model);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int branchId)
        {

            var branch = new Branch();
            branch = branchRepo.GetById(branchId);

            return View(branch);
        }

        [HttpPost]
        public ActionResult DeletePost(Branch model)
        {

            branchRepo.Delete(model);

            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            var branch = branchRepo.Get();
            return View(branch);
        }
    }
}

FirstWebApp/Controllers/CarController.cs
using DAL.Repositories;
using FirstWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApp.Controllers
{
    public class CarController : Controller
    {
        private CarRepository carRepo;
        private BranchRepository branchRepo;

        public CarController()
        {
            carRepo = new CarRepository();
            branchRepo = new BranchRepository();
        }

        public string Temp()
        {
            return "hola";
        }


        public ActionResult Create()
        {
            var viewModel = new CarCreateViewModel();
            viewModel.AvailableBranches = branchRepo.Get();

            return View(viewModel);
        }


        public ActionResult Edit(int carId)
        {

            var viewModel = new CarCreateViewModel();
            viewModel.New = carRepo.GetById(carId);
            viewModel.AvailableBranches = branchRepo.Get();



            return View(viewModel);

        }

        public ActionResult Delete(int carId)
        {

            var viewModel = new CarCreateViewModel();
            viewModel.New = carRepo.GetById(carId);
            viewModel.AvailableBranches = branchRepo.Get();



            return View(viewModel);

        }

        [HttpPost]
        public ActionResult DeletePost(CarCreateViewModel model)
        {

            carRepo.Delete(model.New);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult EditPost(CarCreateViewModel model)
        {
            if (model.New.BranchId <= 0) { }
            else
                carRepo.Edit(model.New);

            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult CreatePost(CarCreateViewModel model)
        {
            if (model.New.BranchId <= 0) { }
            else
                carRepo.Create(model.New);

            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {

            var cars = carRepo.Get();
            return View(cars);
        }


    }
}

FirstWebApp/Controllers/ClientController.cs
using DAL.Moldels;
using DAL.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApp.Controllers
{
    public class ClientController : Controller
    {
        private ClientRepository clientRepo;

        public ClientController()
        {
            clientRepo = new ClientRepository();
        }

       
        //public string Temp()
        //{
        //    return "pakistan";
        //}

        public ActionResult Create()
        {
            var client = new Client();
            return View(client);
        }

        [HttpPost]
        public ActionResult CreatePost(Client model)
        {

            clientRepo.Create(model);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int clientId) // index view must return BranchId 
        {
            var client = new Client();
            client = clientRepo.GetById(clientId);
            return View(client);
        }

        [HttpPost]
        public ActionResult EditPost(Client model)
        {
            if (model.Id <= 0) { }
            else
                clientRepo.Edit(model);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int clientId)
        {

            var client = new Client();
            client = clientRepo.GetById(clientId);

            return View(client);
        }

        [HttpPost]
        public ActionResult DeletePost(Client model)
        {

            clientRepo.Delete(model);

            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            var client = clientRepo.Get();
            return View(client);
        }
    }
}

FirstWebApp/Controllers/HomeController.cs
using DAL.Moldels;
using DAL.Repositories;
using FirstWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApp.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FirstWebApp/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApp.Controllers
{
    public class TestController : Controller
    {

        public ActionResult Temp()
        {
            return Content("barrio ");
        }

        public ActionResult Temp2()
        {
            return Content("fino");
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

FirstWebApp/Views/Bike/Create.cshtml
@model FirstWebApp.ViewModels.BikeCreateViewModel



@using (Html.BeginForm("CreatePost", "Bike", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />
    <br />

    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Model</label>
            @Html.EditorFor(m => m.New.Brand, new { htmlAttributes = new { @class = "form-control", @placeholder = "Modelo" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Color</label>
            @Html.EditorFor(m => m.New.Color, new { htmlAttributes = new { @class = "form-control", @placeholder = "Color" } })
        </div>

        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Branch</label>
            @Html.DropDownListFor(model => model.New.BranchId, Model.AvailableBranches.Select(option => new SelectListItem
            {
                Text = Html.DisplayTextFor(_ => option.Name).ToString(),
                Value = option.Id.ToString(),
                Selected = false
            }), "Branch", new { @class = "form-control", @id = "franchiseList" })

        </div>


    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
    </div>











}

FirstWebApp/Views/Bike/Index.cshtml
@model List<DAL.Moldels.Bike>

<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th>nombre</th>
            <th>color</th>
            <th>branch</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var bike in Model)
        {

            <tr>
                <td>
                    @bike.Brand
                </td>
                <td>
                    @bike.Color
                </td>
                <td>
                    @bike.Branch.Name
                </td>
            </tr>

        }

    </tbody>

</table>

<br />


@Html.ActionLink("Create New Bike", "Create", "Bike", new { @class = "btn btn-primary" })

FirstWebApp/Views/Branch/Create.cshtml
@model DAL.Moldels.Branch



@using (Html.BeginForm("CreatePost", "Branch", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />

    <br />

    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Branch</label>
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Branch Name" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Manager</label>
            @Html.EditorFor(m => m.Manager, new { htmlAttributes = new { @class = "form-control", @placeholder = "Manager Name" } })
        </div>


    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Add</button>
    </div>











}

FirstWebApp/Views/Branch/Delete.cshtml
@model DAL.Moldels.Branch



@using (Html.BeginForm("DeletePost", "Branch", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />
    <br />




    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Branch</label>
            @Html.HiddenFor(m => m.Id)
            @Html.DisplayFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Manager</label>
            @Html.DisplayFor(m => m.Manager, new { htmlAttributes = new { @class = "form-control" } })
        </div>


    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Delete</button>
    </div>











}

FirstWebApp/Views/Branch/Edit.cshtml
@model DAL.Moldels.Branch



@using (Html.BeginForm("EditPost", "Branch", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />
    <br />

    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Model</label>
            @Html.HiddenFor(m => m.Id)
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Branch Name" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Color</label>
            @Html.EditorFor(m => m.Manager, new { htmlAttributes = new { @class = "form-control", @placeholder = "Manager Name" } })
        </div>



    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
    </div>











}

FirstWebApp/Views/Branch/Index.cshtml
@model List<DAL.Moldels.Branch>

<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th>Branch</th>
            <th>Manager</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var branch in Model)
        {

            <tr>
                <td>
                    @branch.Name
                </td>
                <td>
                    @branch.Manager
                </td>
                


                <td>
                    @Html.ActionLink("Edit", "Edit", "Branch", new { @branchId = branch.Id }, new { @class = "btn btn-primary" })
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "Branch", new { @branchId = branch.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>

        }

    </tbody>

</table>

<br />


@Html.ActionLink("Add Branch", "Create", "Branch", new { @class = "btn btn-primary" })

FirstWebApp/Views/Car/Create.cshtml
@model FirstWebApp.ViewModels.CarCreateViewModel



@using (Html.BeginForm("CreatePost", "Car", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />

    <br />

    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Model</label>
            @Html.EditorFor(m => m.New.Brand, new { htmlAttributes = new { @class = "form-control", @placeholder = "Modelo" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Color</label>
            @Html.EditorFor(m => m.New.Color, new { htmlAttributes = new { @class = "form-control", @placeholder = "Color" } })
        </div>

        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Branch</label>
            @Html.DropDownListFor(model => model.New.BranchId, Model.AvailableBranches.Select(option => new SelectListItem
            {
                Text = Html.DisplayTextFor(_ => option.Name).ToString(),
                Value = option.Id.ToString(),
                Selected = false
            }), "Branch", new { @class = "form-control", @id = "franchiseList" })

        </div>


    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
    </div>











}

FirstWebApp/Views/Car/Delete.cshtml
@model FirstWebApp.ViewModels.CarCreateViewModel



@using (Html.BeginForm("DeletePost", "Car", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />
    <br />

    


    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Model</label>
            @Html.HiddenFor(m => m.New.Id)
            @Html.DisplayFor(m => m.New.Brand, new { htmlAttributes = new { @class = "form-control"} })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Color</label>
            @Html.DisplayFor(m => m.New.Color, new { htmlAttributes = new { @class = "form-control"} })
        </div>

        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Branch</label>
            @Html.DisplayFor(m => m.New.Branch.Name, new { htmlAttributes = new { @class = "form-control" } })
        </div>


    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
    </div>











}

FirstWebApp/Views/Car/Edit.cshtml
@model FirstWebApp.ViewModels.CarCreateViewModel



@using (Html.BeginForm("EditPost", "Car", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />
    <br />

    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Model</label>
            @Html.HiddenFor(m => m.New.Id)
            @Html.EditorFor(m => m.New.Brand, new { htmlAttributes = new { @class = "form-control", @placeholder = "Modelo" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Color</label>
            @Html.EditorFor(m => m.New.Color, new { htmlAttributes = new { @class = "form-control", @placeholder = "Color" } })
        </div>

        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Branch</label>
            @Html.DropDownListFor(model => model.New.BranchId, Model.AvailableBranches.Select(option => new SelectListItem
            {
                Text = Html.DisplayTextFor(_ => option.Name).ToString(),
                Value = option.Id.ToString(),
                Selected = false
            }), "Branch", new { @class = "form-control", @id = "franchiseList" })

        </div>


    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
    </div>











}

FirstWebApp/Views/Car/Index.cshtml
@model List<DAL.Moldels.Car>

<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th>nombre</th>
            <th>color</th>
            <th>branch</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model)
        {

            <tr>
                <td>
                    @car.Brand
                </td>
                <td>
                    @car.Color
                </td>
                <td>
                    @car.Branch.Name

                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Car", new { @carId = car.Id }, new { @class = "btn btn-primary" })
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "Car", new { @carId = car.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>

        }

    </tbody>

</table>

<br />


@Html.ActionLink("Create New Car", "Create", "Car", new { @class = "btn btn-primary" })


<script>
    $(document).ready(function () {
        $.ajax({
            url: '/Car/Temp',
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                console.log(data);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(textStatus, errorThrown);
            }
        });
    });
</script>

FirstWebApp/Views/Client/Create.cshtml
@model DAL.Moldels.Client



@using (Html.BeginForm("CreatePost", "Client", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />

    <br />

    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Name</label>
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Client Name" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Address</label>
            @Html.EditorFor(m => m.Adresss, new { htmlAttributes = new { @class = "form-control", @placeholder = "Client Address" } })
        </div>


    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Add</button>
    </div>











}

FirstWebApp/Views/Client/Delete.cshtml
@model DAL.Moldels.Client



@using (Html.BeginForm("DeletePost", "Client", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />
    <br />




    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Name</label>
            @Html.HiddenFor(m => m.Id)
            @Html.DisplayFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Address</label>
            @Html.DisplayFor(m => m.Adresss, new { htmlAttributes = new { @class = "form-control" } })
        </div>


    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Delete</button>
    </div>











}

FirstWebApp/Views/Client/Edit.cshtml
@model DAL.Moldels.Client



@using (Html.BeginForm("EditPost", "Client", FormMethod.Post))
{
    @Html.ValidationSummary(true);

    <br />
    <br />
    <br />

    <div class="row">
        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword1">Name</label>
            @Html.HiddenFor(m => m.Id)
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Client Name" } })
        </div>


        <div class="form-group, col-lg-4">
            <label for="exampleInputPassword2">Address</label>
            @Html.EditorFor(m => m.Adresss, new { htmlAttributes = new { @class = "form-control", @placeholder = "Client Address" } })
        </div>



    </div>


    <br />
    <br />
    <br />
    <br />
    <br />

    <hr />

    <div style="text-align:center;">
        <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
    </div>











}

FirstWebApp/Views/Client/Index.cshtml
@model List<DAL.Moldels.Client>

<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var client in Model)
        {

            <tr>
                <td>
                    @client.Name
                </td>
                <td>
                    @client.Adresss
                </td>



                <td>
                    @Html.ActionLink("Edit", "Edit", "Client", new { @clientId = client.Id }, new { @class = "btn btn-primary" })
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "Client", new { @clientId = client.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>

        }

    </tbody>

</table>

<br />


@Html.ActionLink("Add Client", "Create", "Client", new { @class = "btn btn-primary" })

FirstWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FirstWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FirstWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

FirstWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cars", "Index", "Car")</li>
                    <li>@Html.ActionLink("Bikes", "Index", "Bike")</li>
                    <li>@Html.ActionLink("Branches", "Index", "Branch")</li>
                    <li>@Html.ActionLink("Clients", "Index", "Client")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>

FirstWebApp/Views/Test/Index.cshtml
<h2 id="temp1">Index</h2>



<script>


   


</script>